# Generated by Django 5.2.8 on 2025-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_is_done_task_recurrence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='recurrence_interval',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminders_days_before',
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
