# Generated by Django 5.2.8 on 2025-11-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='y_position',
        ),
        migrations.AddField(
            model_name='stickynote',
            name='position_x',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='position_y',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('pink', 'Pink'), ('green', 'Green'), ('purple', 'Purple')], default='yellow', max_length=20),
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='stickynote',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sticky.tag'),
        ),
    ]
