# Generated by Django 5.2.8 on 2025-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky', '0002_remove_stickynote_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='tags',
        ),
        migrations.RenameField(
            model_name='stickynote',
            old_name='is_archived',
            new_name='pinned',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stickynote',
            name='x',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='stickynote',
            name='y',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='color',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('gray', 'Gray')], default='yellow', max_length=20),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='height',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='width',
            field=models.IntegerField(default=250),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
